---
title: "Week 1"
author: "Bertrand Wilden"
date: "1/5/2022"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
library(rethinking)

theme_set(
  theme_gray(base_size = 13,
             base_family = "Times") +
  theme(panel.grid = element_blank())
)
```


# 1

```{r}
n <- 1e4
p_grid <- seq(from = 0, to = 1, length.out = n)
prior <- rep(1, n)
likelihood <- dbinom(4, 15, prob = p_grid)

posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

tibble(posterior = posterior, 
       p_grid = p_grid) %>% 
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line()
```

# 2

```{r}
n <- 1e4
p_grid <- seq(from = 0, to = 1, length.out = n)
prior2 <- ifelse(p_grid < .5, 0, 1)
likelihood2 <- dbinom(4, 6, prob = p_grid)

posterior2 <- likelihood2 * prior2
posterior2 <- posterior2 / sum(posterior2)

p <- tibble(posterior = posterior2, 
       p_grid = p_grid) %>% 
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line()
p
```

# 3

```{r}
samples <- sample(p_grid ,prob = posterior2, size = n, replace = TRUE)

perc_89 <- PI(samples, prob = .89)
hpdi_89 <- HPDI(samples, prob = .89)

p +
  geom_area(aes(fill = p_grid < perc_89[2] & p_grid > perc_89[1]), alpha = 1) +
  geom_area(aes(fill = p_grid < hpdi_89[2] & p_grid > hpdi_89[1]), alpha = .25) +
  scale_fill_manual(values = c("transparent", "blue", "steelblue"), breaks = NULL) +
  scale_y_continuous(NULL, breaks = NULL)
```

